### ISSUE TITLE
Error: spawnSync xsltproc ENOENT

### ISSUE THREAD

**Issue by saswat3115** [ticapix/node-xsltproc#2]
stack:"Error: spawnSync xsltproc ENOENT\n at Object.spawnSync (internal/child_process.js:990:20)\n at spawnSync (child_process.js:601:24)\n at execFileSync

**Comment by ticapix** [comment]
Hi,

Have you installed xsltproc and is it available in the PATH ?
http://www.sagehill.net/docbookxsl/InstallingAProcessor.html or via your distribution package manager.

best regards

**Comment by saswat3115** [comment]
No. Let me install and check
